/** @type {import('next').NextConfig} */
const nextConfig = {
  // output: "export",
  reactStrictMode: true,
  images: {
    domains: ['blog.olhonocarro.com.br',
      'image1.mobiauto.com.br',
      'assets.volkswagen.com',
'argo.fiat.com.br',
'cronos.fiat.com.br',
'upload.wikimedia.org',
'cdn.iconscout.com',
'uxwing.com',
'iconape.com',
'cdn.icon-icons.com',
'cdn.motor1.com',
'www.webmotors.com.br',
'garagem360.com.br',
'brilhautofiat.com.br',
'production.autoforce.com',
'www.chevrolet.com.br',
'blogger.googleusercontent.com',
's2-autoesporte.glbimg.com',
'cdn.group.renault.com',
'dezeroacem.com.br',
'www.renault.com.br',
'static.virgola.com.br',
'carrosde2024.com.br',
'garagem360.com.br',
'static.virgola.com.br',
'renaultsim.com.br',
'quatrorodas.abril.com.br',
'www.honda.com.br',
'www.automaistv.com.br',
'i.pinimg.com',
'cdn.motor1.com',
'titano.fiat.com.br',
'www.cnnbrasil.com.br',
'www.elcarrocolombiano.com',
 ],
  },

};

export default nextConfig;
